### ISSUE TITLE
Missing 'divergence.nc' file

### ISSUE THREAD

**Issue by felnne** [jshosking/iris-introduction#2]
In testing this, when I get to:
```
# Read a multi-level data file
filename= 'divergence.nc'
```

I get an error:

```
OSError: One or more of the files specified did not exist ['divergence.nc expanded to empty'].
```

I am probably missing some obvious but do I need to download that file from somewhere or should it be created by an initial process?

My IPython notebook is available here: http://scratch-felnne-iris-node1.ext.aws.net.nerc-bas.ac.uk:8888/notebooks/iris-basics.ipynb

Note: That URL will only work within the BAS network - tunneling in from bslcene will work.

It's just a test machine so nothing is valuable - I just wanted to see how easy it was to run starting from a blank machine.

Thanks,
Felix

-----

##### Steps to reproduce

* Launch Miniconda instance as recommended by scitools - in my case *miniconda2-3.18.3* on *Ubuntu 14.04-LTS*

```shell
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get install git

$ conda install system
$ conda install iris

$ git clone https://github.com/jshosking/iris-introduction.git
$ cd iris-introduction
$ wget https://www.unidata.ucar.edu/software/netcdf/examples/ECMWF_ERA-40_subset.nc

$ ipython notebook --ip=10.x.x.x
```

* Quit terminal browser: `q` then `y`
* Open notebook in a proper browser on localhost
* Patch 'In [3]' to put `% matplotlib inline` before importing matlibplot to prevent missing [libSM error|ttps://github.com/conda/conda/issues/1051#issuecomment-111578483]
* Run cells until 'In [7]' which will fail with the missing 'divergence.nc' file

**Comment by jshosking** [comment]
Hi Felix, I hadn't included the file due to licensing reasons but I realise to do the tutorial it is easier to use a pre-made file rather than finding your own.  You can now download a file at:

- https://drive.google.com/file/d/0B5zlcRchTOMlSFM1U3owQ3NzYmc/view?usp=sharing

I'll update the tutorial with the file location.

Also, I'm not sure if it matters but I always specify the channel for my conda iris install:

- conda install -c scitools iris

**Comment by felnne** [comment]
Brilliant, amazingly that all worked - even the plots which I assumed I would have to fiddle with more.

I assume the license is it can't be used outside of BAS?

If so i've re-hosted that file to the BAS SAN and AWS S3 (but with authentication required). If that's not suitable I can remove them.

AWS S3:
`https://s3-eu-west-1.amazonaws.com/bas-science-testing/scratch/python-user-group/iris/jshosking-iris-introduction/divergence.nc`
BAS SAN:
`/data/softwaredist/scratch/python-user-group/iris/jshosking-iris-introduction/divergence.nc`

Thanks for the tip on the conda channel too.

**Comment by jshosking** [comment]
Glad it all worked!  I would suggest replacing the file you have with the new smaller (lower resolution) one I've included in the "Data" directory.

**Comment by felnne** [comment]
Ah cool - I've deleted those files in that case.
